src/Entity/Person.php
<?php

namespace App\Entity;

use App\Entity\Address;
use App\Entity\Ministry;
use App\Entity\WorkingGroup;
use App\Repository\PersonRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use libphonenumber\PhoneNumber;
use Symfony\Component\Serializer\Attribute as Serializer;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * App\Entity\Person
 */
#[ORM\Entity(repositoryClass: PersonRepository::class)]
#[ORM\Table(name: 'person')]
#[Gedmo\Loggable]
class Person
{
    /**
     * Import timestampable behavior.
     */
    use TimestampableEntity;

    const GENDER_MALE = 'm';
    const GENDER_FEMALE = 'f';

    /**
     * Persons whose working status depends on their age.
     */
    const WORKER_STATUS_UNTIL_AGE_LIMIT = 1;

    /**
     * People younger than the age limit years, but not able to work.
     */
    const WORKER_STATUS_INVALID = 2;

    /**
     * People having other ministries like deacons or elders.
     */
    const WORKER_STATUS_OTHER_MINISTRIES = 3;

    /**
     * People not able to work, because of their residence.
     */
    const WORKER_STATUS_UNABLE_RESIDENCE = 4;

    #[ORM\Id]
    #[ORM\Column(type: 'integer')]
    #[ORM\GeneratedValue]
    #[Serializer\Groups(['MinistryCategoryListing'])]
    private ?int $id = null;

    /**
     * Last name can be empty. In that case the last name is taken from
     * address entity (family name)
     */
    #[ORM\Column(type: 'string', length: 30, nullable: true)]
    #[Assert\Length(max: 30)]
    #[Gedmo\Versioned]
    private ?string $lastname = null;

    #[ORM\Column(type: 'string', length: 30)]
    #[Assert\Length(max: 30)]
    #[Gedmo\Versioned]
    #[Serializer\Groups(['MinistryCategoryListing'])]
    private ?string $firstname = null;

    /**
     * Date of birth
     */
    #[ORM\Column(type: 'date', nullable: true)]
    #[Gedmo\Versioned]
    #[Serializer\Groups(['MinistryCategoryListing'])]
    private ?\DateTime $dob = null;

    /**
     * Gender ('m' or 'f')
     */
    #[ORM\Column(type: 'string', length: 1)]
    #[Gedmo\Versioned]
    private ?string $gender = null;

    #[ORM\Column(type: 'phone_number', nullable: true)]
    #[Gedmo\Versioned]
    private ?PhoneNumber $mobile = null;

    #[ORM\Column(type: 'string', length: 100, nullable: true)]
    #[Assert\Email]
    #[Assert\Length(max: 100)]
    #[Gedmo\Versioned]
    private ?string $email = null;

    #[ORM\ManyToOne(targetEntity: Address::class, inversedBy: 'persons', cascade: ['persist'])]
    #[ORM\JoinColumn(name: 'address_id', nullable: false)]
    #[Gedmo\Versioned]
    #[Serializer\Groups(['MinistryCategoryListing'])]
    private ?Address $address = null;

    #[ORM\ManyToOne(targetEntity: 'WorkingGroup', inversedBy: 'persons')]
    #[ORM\JoinColumn(name: 'working_group_id', nullable: true, onDelete: 'SET NULL')]
    #[Gedmo\Versioned]
    private ?WorkingGroup $workingGroup = null;

    /**
     * Defines whether person is able to work or not.
     * See class constants self::WORKER_STATUS_*
     */
    #[ORM\Column(name: 'worker_status', type: 'smallint', nullable: false)]
    #[Gedmo\Versioned]
    private int $workerStatus = self::WORKER_STATUS_UNTIL_AGE_LIMIT;

    /**
     * @var string|null
     */
    #[ORM\Column(type: 'text', nullable: true)]
    private ?string $notice = null;

    #[ORM\Column(type: 'integer', nullable: true, unique: true)]
    private ?int $churchToolsId = null;

    #[ORM\OneToOne(targetEntity: 'WorkingGroup', mappedBy: 'leader')]
    private ?WorkingGroup $leaderOf = null;

    #[ORM\ManyToMany(targetEntity: 'Ministry', mappedBy: 'responsibles', cascade: ['remove'])]
    private Collection $ministries;

    /**
     * Constructor
     */
    public function __construct(?Address $address = null)
    {
        $address && $this->setAddress($address);
        $this->ministries = new ArrayCollection();
    }

    /**
     * Get id
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(?string $lastname): self
    {
        $this->lastname = $lastname;
        return $this;
    }

    /**
     * Get the firstname, name prefix and lastname concated.
     *
     * @return string
     */
    public function getFirstnameAndLastname(): string
    {
        return $this->getFirstname() . ' '
            . ($this->getAddress()->getNamePrefix() ? $this->getAddress()->getNamePrefix() . ' ' : '')
            . ($this->getLastname() ?: $this->getAddress()->getFamilyName());
    }

    /**
     * Get the display name (firstname and lastname) with year of birth.
     */
    public function getDisplayNameDob(): string
    {
        $year = $this->getDob() ? $this->getDob()->format('Y') : '0000';
        return $this->getFirstnameAndLastname() . ' (' . $year . ')';
    }

    /**
     * Get the concated lastname, firstname and name prefix.
     */
    public function getLastnameAndFirstname(): string
    {
        return ($this->getLastname() ?: $this->getAddress()->getFamilyName()) . ', ' . $this->getFirstname()
            . ($this->getAddress()->getNamePrefix() ? ' ' . $this->getAddress()->getNamePrefix() : '');
    }

    /**
     * Get the concated lastname, firstname, name prefix and year of birth.
     *
     * @return string
     */
    public function getLastnameFirstnameAndDob(): string
    {
        $year = $this->getDob() ? $this->getDob()->format('Y') : '0000';
        return $this->getLastnameAndFirstname() . ' (' . $year . ')';
    }

    /**
     * Set firstname
     *
     * @param string $firstname
     * @return Person
     */
    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    /**
     * Get firstname
     */
    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    /**
     * Set the date of birth
     *
     * @return $this
     */
    public function setDob(?\DateTime $dob): self
    {
        $this->dob = $dob;

        return $this;
    }

    /**
     * Get the date of birth
     */
    public function getDob(): ?\DateTime
    {
        return $this->dob;
    }

    /**
     * Get the current age of the person.
     */
    public function getAge(): ?int
    {
        if (!$this->dob) {
            return null;
        }

        $diff = $this->dob->diff(new \DateTime(), true);
        /* @var $diff \DateInterval */

        return $diff->y;
    }

    public function getGender(): ?string
    {
        return $this->gender;
    }

    public function setGender(?string $gender)
    {
        $this->gender = $gender;
        return $this;
    }

    /**
     * Set mobile
     *
     * @return $this
     */
    public function setMobile(?PhoneNumber $mobile): self
    {
        if ($this->mobile && $mobile && $this->mobile->equals($mobile)) {
            return $this;
        }

        $this->mobile = $mobile;

        return $this;
    }

    /**
     * Get mobile
     */
    public function getMobile(): ?PhoneNumber
    {
        return $this->mobile;
    }

    /**
     * Set email
     *
     * @return $this
     */
    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Get email
     */
    public function getEmail(): ?string
    {
        return $this->email;
    }

    /**
     * Set address
     *
     * @return $this
     */
    public function setAddress(Address $address): self
    {
        $this->address = $address;
        if (!$address->getPersons()->contains($this)) {
            $address->getPersons()->add($this);
        }
        return $this;
    }

    /**
     * Get address
     */
    public function getAddress(): ?Address
    {
        return $this->address;
    }

    /**
     * Set workingGroup
     *
     * @return $this
     */
    public function setWorkingGroup(?WorkingGroup $workingGroup): self
    {
        if ($this->gender && $workingGroup && $this->gender !== $workingGroup->getGender()) {
            throw new \InvalidArgumentException('This person is not compatible to the passed working group.');
        }

        $this->workingGroup = $workingGroup;

        if ($workingGroup && !$workingGroup->getPersons()->contains($this)) {
            $workingGroup->getPersons()->add($this);
        }

        return $this;
    }

    /**
     * Get workingGroup
     *
     * @return WorkingGroup
     */
    public function getWorkingGroup(): ?WorkingGroup
    {
        return $this->workingGroup;
    }

    public function getWorkerStatus(): int
    {
        return $this->workerStatus;
    }

    public function setWorkerStatus(int $workerStatus): self
    {
        $allStatus = self::getAllWorkerStatus();
        if (!isset($allStatus[$workerStatus])) {
            throw new \InvalidArgumentException('Given worker status is invalid.');
        }
        $this->workerStatus = $workerStatus;
        return $this;
    }

    /**
     * Get the notice.
     *
     * @return string|null
     */
    public function getNotice(): ?string
    {
        return $this->notice;
    }

    /**
     * Set the notice
     */
    public function setNotice(?string $notice)
    {
        $this->notice = $notice;
    }

    public function getChurchToolsId(): ?int
    {
        return $this->churchToolsId;
    }

    public function setChurchToolsId(int $churchToolsId): static
    {
        if ($this->churchToolsId && $this->churchToolsId !== $churchToolsId) {
            throw new \LogicException('The ChurchTools ID cannot be changed.');
        }

        $this->churchToolsId = $churchToolsId;
        return $this;
    }

    /**
     * @return array<int, string>
     */

src/Controller/MinistryCategoryController.php
<?php

namespace App\Controller;

use App\Entity\Ministry\Category;
use App\Form\Ministry\CategoryType;
use App\Repository\Ministry\CategoryRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Serializer\SerializerInterface;

/**
 * App\Controller\MinistryCategoryController
 */
#[Route(path: '/ministry_category')]
class MinistryCategoryController extends AbstractController
{
    /**
     * Lists all Address entities.
     */
    #[Route('/', name: 'app.ministry_category.index', methods: ['GET'])]
    public function index(CategoryRepository $repo): Response
    {
        $ministryCategories = $repo->findBy([], ['position' => 'asc']);

        return $this->render('/ministry_category/index.html.twig', array(
            'ministryCategories' => $ministryCategories,
        ));
    }

    #[Route('/create', name: 'app.ministry_category.create')]
    public function create(Request $request, EntityManagerInterface $em): Response
    {
        $category = new Category();

        $form = $this->createForm(CategoryType::class, $category);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em->persist($category);
            $em->flush();

            $this->addFlash('success', 'The entry has been created.');

            return $this->redirectToRoute('app.ministry_category.edit', ['id' => $category->getId()]);
        }

        return $this->render('ministry_category/form.html.twig', [
            'category' => $category,
            'form' => $form->createView(),
        ]);
    }

    #[Route(path: '/{id}/edit', name: 'app.ministry_category.edit')]
    public function edit(Category $category, Request $request, EntityManagerInterface $em): Response
    {
        $form = $this->createForm(CategoryType::class, $category);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em->flush();

            $this->addFlash('success', 'All changes have been saved.');

            return $this->redirectToRoute('app.ministry_category.edit', ['id' => $category->getId()]);
        }

        return $this->render('ministry_category/form.html.twig', [
            'category' => $category,
            'form' => $form->createView(),
        ]);
    }

    #[Route(path: '/{id}/delete', name: 'app.ministry_category.delete', methods: ['DELETE'])]
    public function delete(Category $category, Request $request, EntityManagerInterface $em): Response
    {
        if (!$this->isCsrfTokenValid('delete_ministry_category', $request->request->get('_token'))) {
            throw $this->createAccessDeniedException('Invalid token.');
        }

        $em->remove($category);
        $em->flush();

        $this->addFlash('success', 'The entry has been deleted.');

        return $this->redirectToRoute('app.ministry_category.index');
    }

    /**
     * Edits an existing Address entity.
     */
    #[Route('/', name: 'app.ministry_category.update', methods: ['POST'], requirements: ['_format' => 'json'])]
    public function update(
        Request $request,
        SerializerInterface $serializer,
        EntityManagerInterface $em,
        CategoryRepository $repo,
    ): Response {
        if ('json' != $request->getContentType()) {
            throw new \InvalidArgumentException('Wrong content type provided. JSON is expected.');
        }

        $clientMinistryCategories = $request->toArray();

        $ministryNames = [];
        foreach ($clientMinistryCategories as $c) {
            foreach ($c['ministries'] as $m) {
                if (isset($ministryNames[$m['name']]) && $m['name'] != 'Materialbüro') {
                    throw new \InvalidArgumentException('ministry ' . $m['name'] . ' doppelt.');
                }
                $ministryNames[$m['name']] = $m['name'];
            }
        }

        $categories = $repo->findAll();

        $form = $this->createCategoriesForm($categories);
        $form->submit($clientMinistryCategories);

        if (!$form->isValid()) {
            return new JsonResponse('Invalid entity', JsonResponse::HTTP_BAD_REQUEST);
        }

        $ministryNames = [];
        foreach ($categories as $c) {
            foreach ($c->getMinistries() as $m) {
                if (isset($ministryNames[$m->getName()]) && $m->getName() != 'Materialbüro') {
                    throw new \InvalidArgumentException('ministry ' . $m->getName() . ' doppelt, nach form mapping.');
                }
                $ministryNames[$m->getName()] = $m->getName();
            }
        }

        foreach ($form->getData() as $category) {
            $em->persist($category);
        }
        $em->flush();

        // response
        $context = ['groups' => ['MinistryCategoryListing']];
        $data = $serializer->normalize($categories, 'json', $context);

        return new JsonResponse($data);
    }


    private function createCategoriesForm(array $categories)
    {
        $form = $this->createForm(CollectionType::class, $categories, [
            'entry_type' => CategoryType::class,
            'label' => false,
            'prototype' => true,
            'allow_add' => true,
            'by_reference' => false,
            'allow_delete' => true,
            'entry_options' => [
                'label' => false,
            ],
            'csrf_protection' => false,
        ]);
        return $form;
    }
}

templates/ministry_category/form.html.twig
{% extends 'base.html.twig' %}

{% form_theme form _self %}

{% block title %}
    {% if category.id %}
        {{ category.name }} - {% trans %}Ministry Category{% endtrans %} - {{ parent() }}
    {% else %}
        {% trans %}Create Ministry Category{% endtrans %} - {{ parent() }}
    {% endif %}
{% endblock %}

{% block body %}
    {{ form_start(form) }}

    <div class="d-flex align-items-center mb-3">
        <h2 class="mr-auto">
            {% if category.id %}
                {% trans %}Edit Ministry Category{% endtrans %}
            {% else %}
                {% trans %}Create Ministry Category{% endtrans %}
            {% endif %}
        </h2>
        <a class="btn btn-outline-dark" title="{% trans %}Back to List{% endtrans %}"
           href="{{ path('app.ministry_category.index') }}#{{ category.name | slug }}">
            <i class="bi bi-chevron-left"></i> {% trans %}Back{% endtrans %}
        </a>
        <button type="submit" class="btn btn-primary ml-2">
            <i class="bi bi-save"></i> {% trans %}Save{% endtrans %}
        </button>
        {% if category.id > 0 %}
            <button type="button" class="btn btn-danger ml-2" data-toggle="modal" data-target="#delete-modal">
                <i class="bi bi-trash"></i> {% trans %}Delete{% endtrans %}
            </button>
        {% endif %}
    </div>


    {{ form_errors(form) }}
    <div class="card mb-3">
        <div class="card-header">
            {% trans %}Master data{% endtrans %}
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-lg-6">
                    {{ form_row(form.position) }}
                    {{ form_row(form.name) }}
                </div>
                <div class="col-lg-6">
                    {{ form_row(form.responsible) }}
                </div>
            </div>
        </div>
    </div>

    <div class="card">
        <div class="card-header">
            {% trans %}Ministries{% endtrans %}
        </div>
        <div class="card-body">
            {{ form_row(form.ministries) }}

            <button type="button" class="btn btn-sm btn-primary" add-collection-item="#{{ form.ministries.vars.id }}">
                <i class="bi bi-plus-lg"></i> {% trans %}Add ministry{% endtrans %}
            </button>
        </div>
    </div>

    {{ form_rest(form) }}
    {{ form_end(form) }}

    {% if category.id %}
        <!-- Modal -->
        <div class="modal fade" id="delete-modal" tabindex="-1" aria-labelledby="delete-modal-title" aria-hidden="true">
            <div class="modal-dialog">
                <form class="modal-content" action="{{ path('app.ministry_category.delete', {'id': category.id}) }}" method="post">
                    <input type="hidden" name="_method" value="delete">
                    <input type="hidden" name="_token" value="{{ csrf_token('delete_ministry_category') }}">
                    <div class="modal-header">
                        <h5 class="modal-title" id="delete-modal-title">{% trans %}Delete Record{% endtrans %}</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="{% trans %}Close{% endtrans %}">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        {% trans %}Do you really want to delete this entry?{% endtrans %}
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-outline-dark" data-dismiss="modal">{% trans %}Cancel{% endtrans %}</button>
                        <button type="submit" class="btn btn-danger">{% trans %}Delete{% endtrans %}</button>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

{% block ministry_widget %}
    <div class="row">
        <div class="col-md-3">
            {{ form_row(form.position) }}
            {{ form_row(form.name) }}
        </div>
        <div class="col-md-3">
            {{ form_row(form.description) }}
        </div>
        <div class="col-md-3">
            {{ form_row(form.responsibles) }}
            <button type="button" class="btn btn-sm btn-primary" add-collection-item="#{{ form.responsibles.vars.id }}">
                <i class="bi bi-plus-lg"></i> {% trans %}Add responsible{% endtrans %}
            </button>
        </div>
        <div class="col-md-3 text-right">
            <button type="button" class="btn btn-sm btn-danger" remove-collection-item>
                <i class="bi bi-trash"></i> {% trans %}Remove{% endtrans %}
            </button>
        </div>
    </div>
{% endblock %}

{% block _category_ministries_entry_responsibles_entry_widget %}
    {{ block('choice_widget') }}
    <button type="button" class="btn btn-sm btn-danger" remove-collection-item>
        <i class="bi bi-trash"></i>
    </button>
{% endblock %}

templates/ministry_category/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {% trans %}Ministries{% endtrans %} - {{ parent() }}
{% endblock %}

{% block body %}
    <div class="d-flex align-items-center mb-3">
        <h2 class="mr-auto">{% trans %}Ministries{% endtrans %}</h2>
        <a href="{{ path('app.ministry_category.create') }}" class="btn btn-success" title="{% trans %}Add Ministry Category{% endtrans %}">
            <i class="bi bi-plus-lg"></i>
        </a>
    </div>


    <table class="table table-bordered ministry-category-list">
        <thead>
            <tr>
                <th>{% trans %}Pos.{% endtrans %}</th>
                <th>{% trans %}Bereich{% endtrans %}</th>
                <th>{% trans %}Pos.{% endtrans %}</th>
                <th>{% trans %}Unterbereich{% endtrans %}</th>
                <th>{% trans %}Tasks{% endtrans %}</th>
                <th>{% trans %}Responsibles{% endtrans %}</th>
                <th class="text-center">{% trans %}Actions{% endtrans %}</th>
            </tr>
        </thead>
        <tbody>
            {% for ministryCategory in ministryCategories %}
                <tr id="{{ ministryCategory.name | slug }}">
                    <td rowspan="{{ ministryCategory.ministries | length + 1 }}">
                        {{ ministryCategory.position }}
                    </td>
                    <td rowspan="{{ ministryCategory.ministries | length + 1 }}">
                        {{ ministryCategory.name }}
                    </td>
                    <td colspan="3">
                        {% trans %}Main Responsible{% endtrans %}
                    </td>
                    <td>
                        {{ ministryCategory.responsible ? ministryCategory.responsible.displayNameDob : null }}
                    </td>
                    <td class="text-center" rowspan="{{ ministryCategory.ministries | length + 1 }}">
                        <a href="{{ path('app.ministry_category.edit', {'id': ministryCategory.id}) }}"
                           class="btn btn-outline-dark btn-sm" title="{% trans %}Edit Ministry Category{% endtrans %}">
                            <i class="bi bi-pencil"></i>
                        </a>
                        <button type="button" class="btn btn-danger btn-sm" title="{% trans %}Delete record{% endtrans %}" delete-ministry-category="{{ ministryCategory.id }}">
                            <i class="bi bi-trash"></i>
                        </button>
                    </td>
                </tr>
                {% for ministry in ministryCategory.ministries %}
                    <tr>
                        <td>{{ ministry.position }}</td>
                        <td>{{ ministry.name }}</td>
                        <td>{{ ministry.description }}</td>
                        <td>
                            {% for person in ministry.responsibles %}
                                {{ person.displayNameDob }}<br>
                            {% endfor %}
                        </td>
                    </tr>
                {% endfor %}
            {% endfor %}
        </tbody>
        <tfoot>
            {% if ministryCategories | length == 0 %}
                <tr>
                    <td colspan="7">
                        {% trans %}There are no entries existing, yet.{% endtrans %}
                    </td>
                </tr>
            {% endif %}
        </tfoot>
    </table>

    <!-- Modal -->
    <div class="modal fade" id="delete-modal" tabindex="-1" aria-labelledby="delete-modal-title" aria-hidden="true">
        <div class="modal-dialog">
            <form class="modal-content" action="{{ path('app.ministry_category.delete', {'id': '_ID_'}) }}" method="post">
                <input type="hidden" name="_method" value="delete">
                <input type="hidden" name="_token" value="{{ csrf_token('delete_ministry_category') }}">
                <div class="modal-header">
                    <h5 class="modal-title" id="delete-modal-title">{% trans %}Delete Record{% endtrans %}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="{% trans %}Close{% endtrans %}">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    {% trans %}Do you really want to delete this entry?{% endtrans %}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-dark" data-dismiss="modal">{% trans %}Cancel{% endtrans %}</button>
                    <button type="submit" class="btn btn-danger">{% trans %}Delete{% endtrans %}</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('ministry_categories.index') }}
{% endblock %}