src/Entity/Person.php
<?php

namespace App\Entity;

use App\Entity\Address;
use App\Entity\Ministry;
use App\Entity\WorkingGroup;
use App\Repository\PersonRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use libphonenumber\PhoneNumber;
use Symfony\Component\Serializer\Attribute as Serializer;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * App\Entity\Person
 */
#[ORM\Entity(repositoryClass: PersonRepository::class)]
#[ORM\Table(name: 'person')]
#[Gedmo\Loggable]
class Person
{
    /**
     * Import timestampable behavior.
     */
    use TimestampableEntity;

    const GENDER_MALE = 'm';
    const GENDER_FEMALE = 'f';

    /**
     * Persons whose working status depends on their age.
     */
    const WORKER_STATUS_UNTIL_AGE_LIMIT = 1;

    /**
     * People younger than the age limit years, but not able to work.
     */
    const WORKER_STATUS_INVALID = 2;

    /**
     * People having other ministries like deacons or elders.
     */
    const WORKER_STATUS_OTHER_MINISTRIES = 3;

    /**
     * People not able to work, because of their residence.
     */
    const WORKER_STATUS_UNABLE_RESIDENCE = 4;

    #[ORM\Id]
    #[ORM\Column(type: 'integer')]
    #[ORM\GeneratedValue]
    #[Serializer\Groups(['MinistryCategoryListing'])]
    private ?int $id = null;

    /**
     * Last name can be empty. In that case the last name is taken from
     * address entity (family name)
     */
    #[ORM\Column(type: 'string', length: 30, nullable: true)]
    #[Assert\Length(max: 30)]
    #[Gedmo\Versioned]
    private ?string $lastname = null;

    #[ORM\Column(type: 'string', length: 30)]
    #[Assert\Length(max: 30)]
    #[Gedmo\Versioned]
    #[Serializer\Groups(['MinistryCategoryListing'])]
    private ?string $firstname = null;

    /**
     * Date of birth
     */
    #[ORM\Column(type: 'date', nullable: true)]
    #[Gedmo\Versioned]
    #[Serializer\Groups(['MinistryCategoryListing'])]
    private ?\DateTime $dob = null;

    /**
     * Gender ('m' or 'f')
     */
    #[ORM\Column(type: 'string', length: 1)]
    #[Gedmo\Versioned]
    private ?string $gender = null;

    #[ORM\Column(type: 'phone_number', nullable: true)]
    #[Gedmo\Versioned]
    private ?PhoneNumber $mobile = null;

    #[ORM\Column(type: 'string', length: 100, nullable: true)]
    #[Assert\Email]
    #[Assert\Length(max: 100)]
    #[Gedmo\Versioned]
    private ?string $email = null;

    #[ORM\ManyToOne(targetEntity: Address::class, inversedBy: 'persons', cascade: ['persist'])]
    #[ORM\JoinColumn(name: 'address_id', nullable: false)]
    #[Gedmo\Versioned]
    #[Serializer\Groups(['MinistryCategoryListing'])]
    private ?Address $address = null;

    #[ORM\ManyToOne(targetEntity: 'WorkingGroup', inversedBy: 'persons')]
    #[ORM\JoinColumn(name: 'working_group_id', nullable: true, onDelete: 'SET NULL')]
    #[Gedmo\Versioned]
    private ?WorkingGroup $workingGroup = null;

    /**
     * Defines whether person is able to work or not.
     * See class constants self::WORKER_STATUS_*
     */
    #[ORM\Column(name: 'worker_status', type: 'smallint', nullable: false)]
    #[Gedmo\Versioned]
    private int $workerStatus = self::WORKER_STATUS_UNTIL_AGE_LIMIT;

    /**
     * @var string|null
     */
    #[ORM\Column(type: 'text', nullable: true)]
    private ?string $notice = null;

    #[ORM\Column(type: 'integer', nullable: true, unique: true)]
    private ?int $churchToolsId = null;

    #[ORM\OneToOne(targetEntity: 'WorkingGroup', mappedBy: 'leader')]
    private ?WorkingGroup $leaderOf = null;

    #[ORM\ManyToMany(targetEntity: 'Ministry', mappedBy: 'responsibles', cascade: ['remove'])]
    private Collection $ministries;

    /**
     * Constructor
     */
    public function __construct(?Address $address = null)
    {
        $address && $this->setAddress($address);
        $this->ministries = new ArrayCollection();
    }

    /**
     * Get id
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(?string $lastname): self
    {
        $this->lastname = $lastname;
        return $this;
    }

    /**
     * Get the firstname, name prefix and lastname concated.
     *
     * @return string
     */
    public function getFirstnameAndLastname(): string
    {
        return $this->getFirstname() . ' '
            . ($this->getAddress()->getNamePrefix() ? $this->getAddress()->getNamePrefix() . ' ' : '')
            . ($this->getLastname() ?: $this->getAddress()->getFamilyName());
    }

    /**
     * Get the display name (firstname and lastname) with year of birth.
     */
    public function getDisplayNameDob(): string
    {
        $year = $this->getDob() ? $this->getDob()->format('Y') : '0000';
        return $this->getFirstnameAndLastname() . ' (' . $year . ')';
    }

    /**
     * Get the concated lastname, firstname and name prefix.
     */
    public function getLastnameAndFirstname(): string
    {
        return ($this->getLastname() ?: $this->getAddress()->getFamilyName()) . ', ' . $this->getFirstname()
            . ($this->getAddress()->getNamePrefix() ? ' ' . $this->getAddress()->getNamePrefix() : '');
    }

    /**
     * Get the concated lastname, firstname, name prefix and year of birth.
     *
     * @return string
     */
    public function getLastnameFirstnameAndDob(): string
    {
        $year = $this->getDob() ? $this->getDob()->format('Y') : '0000';
        return $this->getLastnameAndFirstname() . ' (' . $year . ')';
    }

    /**
     * Set firstname
     *
     * @param string $firstname
     * @return Person
     */
    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    /**
     * Get firstname
     */
    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    /**
     * Set the date of birth
     *
     * @return $this
     */
    public function setDob(?\DateTime $dob): self
    {
        $this->dob = $dob;

        return $this;
    }

    /**
     * Get the date of birth
     */
    public function getDob(): ?\DateTime
    {
        return $this->dob;
    }

    /**
     * Get the current age of the person.
     */
    public function getAge(): ?int
    {
        if (!$this->dob) {
            return null;
        }

        $diff = $this->dob->diff(new \DateTime(), true);
        /* @var $diff \DateInterval */

        return $diff->y;
    }

    public function getGender(): ?string
    {
        return $this->gender;
    }

    public function setGender(?string $gender)
    {
        $this->gender = $gender;
        return $this;
    }

    /**
     * Set mobile
     *
     * @return $this
     */
    public function setMobile(?PhoneNumber $mobile): self
    {
        if ($this->mobile && $mobile && $this->mobile->equals($mobile)) {
            return $this;
        }

        $this->mobile = $mobile;

        return $this;
    }

    /**
     * Get mobile
     */
    public function getMobile(): ?PhoneNumber
    {
        return $this->mobile;
    }

    /**
     * Set email
     *
     * @return $this
     */
    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Get email
     */
    public function getEmail(): ?string
    {
        return $this->email;
    }

    /**
     * Set address
     *
     * @return $this
     */
    public function setAddress(Address $address): self
    {
        $this->address = $address;
        if (!$address->getPersons()->contains($this)) {
            $address->getPersons()->add($this);
        }
        return $this;
    }

    /**
     * Get address
     */
    public function getAddress(): ?Address
    {
        return $this->address;
    }

    /**
     * Set workingGroup
     *
     * @return $this
     */
    public function setWorkingGroup(?WorkingGroup $workingGroup): self
    {
        if ($this->gender && $workingGroup && $this->gender !== $workingGroup->getGender()) {
            throw new \InvalidArgumentException('This person is not compatible to the passed working group.');
        }

        $this->workingGroup = $workingGroup;

        if ($workingGroup && !$workingGroup->getPersons()->contains($this)) {
            $workingGroup->getPersons()->add($this);
        }

        return $this;
    }

    /**
     * Get workingGroup
     *
     * @return WorkingGroup
     */
    public function getWorkingGroup(): ?WorkingGroup
    {
        return $this->workingGroup;
    }

    public function getWorkerStatus(): int
    {
        return $this->workerStatus;
    }

    public function setWorkerStatus(int $workerStatus): self
    {
        $allStatus = self::getAllWorkerStatus();
        if (!isset($allStatus[$workerStatus])) {
            throw new \InvalidArgumentException('Given worker status is invalid.');
        }
        $this->workerStatus = $workerStatus;
        return $this;
    }

    /**
     * Get the notice.
     *
     * @return string|null
     */
    public function getNotice(): ?string
    {
        return $this->notice;
    }

    /**
     * Set the notice
     */
    public function setNotice(?string $notice)
    {
        $this->notice = $notice;
    }

    public function getChurchToolsId(): ?int
    {
        return $this->churchToolsId;
    }

    public function setChurchToolsId(int $churchToolsId): static
    {
        if ($this->churchToolsId && $this->churchToolsId !== $churchToolsId) {
            throw new \LogicException('The ChurchTools ID cannot be changed.');
        }

        $this->churchToolsId = $churchToolsId;
        return $this;
    }

    /**
     * @return array<int, string>
     */

src/Entity/WorkingGroup.php
<?php

namespace App\Entity;

use App\Entity\Person;
use App\Repository\WorkingGroupRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Contracts\Translation\TranslatorInterface;

/**
 * App\Entity\WorkingGroup
 */
#[ORM\Entity(repositoryClass: WorkingGroupRepository::class)]
#[ORM\Table(name: 'working_group')]
#[ORM\UniqueConstraint(name: 'uniqueGenderNumber', columns: ['gender', 'number'])]
class WorkingGroup
{
    #[ORM\Id]
    #[ORM\Column(type: 'integer')]
    #[ORM\GeneratedValue]
    private ?int $id = null;

    #[ORM\Column(type: 'integer')]
    private ?int $number = null;

    #[ORM\Column(type: 'string', length: 1)]
    private ?string $gender = null;

    #[ORM\Column(type: 'integer', nullable: true, unique: true)]
    private ?int $churchToolsId = null;

    /**
     * @var Collection<int, Person>
     */
    #[ORM\OneToMany(targetEntity: Person::class, mappedBy: 'workingGroup')]
    private Collection $persons;

    #[ORM\OneToOne(targetEntity: Person::class, inversedBy: 'leaderOf')]
    #[ORM\JoinColumn(name: 'leader_person_id', nullable: true)]
    private ?Person $leader = null;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->persons = new ArrayCollection();
    }

    /**
     * Get id
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * Set gender
     *
     * @param string $gender
     * @return $this
     */
    public function setGender(string $gender): static
    {
        if ($this->getId() > 0 && $this->getGender() != $gender) {
            throw new \RuntimeException('It is not possible to change the gender of a working group.');
        }
        $this->gender = $gender;
        return $this;
    }

    /**
     * Get gender
     */
    public function getGender(): ?string
    {
        return $this->gender;
    }

    public function getChurchToolsId(): ?int
    {
        return $this->churchToolsId;
    }

    public function setChurchToolsId(?int $churchToolsId): static
    {
        $this->churchToolsId = $churchToolsId;
        return $this;
    }

    /**
     * Add persons
     *
     * @return $this
     */
    public function addPerson(Person $person): static
    {
        if ($this->gender !== $person->getGender()) {
            throw new InvalidArgumentException('This working group is not compatible to the passed person.');
        }

        if (!$this->persons->contains($person)) {
            $this->persons->add($person);
        }

        $person->setWorkingGroup($this);

        return $this;
    }

    /**
     * Remove persons
     */
    public function removePerson(Person $person)
    {
        $this->persons->removeElement($person);
        $person->setWorkingGroup(null);
    }

    /**
     * Get persons
     *
     * @return Collection<int, Person>
     */
    public function getPersons(): Collection
    {
        return $this->persons;
    }

    /**
     * Set leader
     *
     * @return $this
     */
    public function setLeader(?Person $leader): static
    {
        $this->leader = $leader;

        if ($leader) {
            $leader->setWorkingGroup($this);
        }

        return $this;
    }

    /**
     * Get leader
     */
    public function getLeader(): ?Person
    {
        return $this->leader;
    }

    /**
     * Set number
     *
     * @return $this
     */
    public function setNumber(int $number): static
    {
        $this->number = $number;
        return $this;
    }

    /**
     * Get number
     */
    public function getNumber(): ?int
    {
        return $this->number;
    }

    public function getDisplayName(TranslatorInterface $translator = null): string
    {
        $gender = $this->getGender() == Person::GENDER_FEMALE ? 'Female' : 'Male';

        if ($translator) {
            return $translator->trans($gender . ' Group') . ' ' . $this->getNumber();
        }

        return $gender . ' Group' . ' ' . $this->getNumber();
    }

    public function getAvgAge(): float
    {
        $currentYear = date('Y');
        $years = 0;
        $numberOfPersons = 0;

        if ($this->getLeader() && $this->getLeader()->getDob()) {
            $years += $currentYear - $this->getLeader()->getDob()->format('Y');
            $numberOfPersons++;
        }

        foreach ($this->getPersons() as $person) {
            // The leader should not be counted again
            if ($person->getDob() && $person !== $this->getLeader()) {
                $years += $currentYear - $person->getDob()->format('Y');
                $numberOfPersons++;
            }
        }

        if (0 === $numberOfPersons) {
            return 0.0;
        }

        return $years / $numberOfPersons;
    }

    public function getVarianceOfAge(): float
    {
        $avg = $this->getAvgAge();
        $powedSum = 0;
        $numberOfPersons = 0;

        if ($this->getLeader() && $this->getLeader()->getDob()) {
            $year = date('Y') - $this->getLeader()->getDob()->format('Y');
            $powedSum += pow($year - $avg, 2);
            $numberOfPersons++;
        }

        foreach ($this->getPersons() as $person) {
            // The leader should not be counted again
            if ($person->getDob() && $person !== $this->getLeader()) {
                $year = date('Y') - $person->getDob()->format('Y');
                $powedSum += pow($year - $avg, 2);
                $numberOfPersons++;
            }
        }
        return $powedSum / $numberOfPersons;
    }

    public function getStandardDeviationOfAge(): float
    {
        return sqrt($this->getVarianceOfAge());
    }
}

templates/working_group/assignables.html.twig
{% extends 'base.html.twig' %}

{% block body -%}
    <h2>{% trans %}Persons assignable to a Working Group{% endtrans %}</h2>

    <form action="{{ path('app.workinggroup.assign') }}" method="post">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>{% trans %}Last Name{% endtrans %}</th>
                    <th>{% trans %}First Name{% endtrans %}</th>
                    <th>{% trans %}DOB{% endtrans %}</th>
                    <th>{% trans %}Able to work{% endtrans %}</th>
                    <th>{% trans %}Group{% endtrans %}</th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <tbody>
            {% for person in persons %}
                <tr>
                    <td>
                        {{ person.address.familyName }}
                    </td>
                    <td>
                        {{ person.firstname }}
                    </td>
                    <td>
                        {{ person.dob ? person.dob | format_date('medium') : '' }}
                    </td>
                    <td>
                        {% trans %}Yes{% endtrans %}
                    </td>
                    <td>
                        <select name="person-to-group[{{ person.id }}]">
                            <option value=""></option>
                            {% for group in (working_groups | filter(group => group.gender == person.gender)) %}
                                <option value="{{ group.id }}">
                                    {%- if group.gender == 'f' %}
                                        {%- trans %}Group of Women{% endtrans %} {{ group.number }}
                                    {%- else %}
                                        {%- trans %}Group of Men{% endtrans %} {{ group.number }}
                                    {%- endif %}
                                </option>
                            {% endfor %}
                        </select>
                    </td>
                    <td>
                        <a class="btn btn-sm btn-outline-dark" href="{{ path('app.person.edit', {'id': person.id}) }}">
                            <i class="bi bi-pencil"></i>
                        </a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="4">
                        {% trans %}There are no entries existing, yet.{% endtrans %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <button type="submit" class="btn btn-primary">
            {% trans %}Save{% endtrans %}
        </button>
    </form>
{% endblock %}

templates/working_group/form.html.twig
{% extends 'base.html.twig' %}

{% form_theme form _self %}

{% block title %}
    {% trans %}Working Group{% endtrans %} - {{ parent() }}
{% endblock %}

{% block body -%}
    {{ form_start(form) }}
    <div class="d-flex align-items-center mb-3">
        <h2 class="mr-auto">
            {% trans %}Working Group{% endtrans %}
        </h2>
        <a class="btn btn-outline-dark"
         href="{{ path('app.workinggroup.index') }}"
         title="{% trans %}Back to List{% endtrans %}">
            <i class="bi bi-chevron-left"></i> {% trans %}Back{% endtrans %}
        </a>
        <button type="submit" class="btn btn-primary ml-2">
            <i class="bi bi-save"></i> {% trans %}Save{% endtrans %}
        </button>
        {% if workingGroup.id > 0 %}
            <a class="btn btn-danger ml-2"
             href="{{ path('app.workinggroup.delete', {'id': workingGroup.id}) }}"
             title="{% trans %}Delete Working Group{% endtrans %}"
             onclick="return confirm('{% trans %}Do you really want to delete this entry?{% endtrans %}')">
                <i class="bi bi-trash"></i> {% trans %}Delete{% endtrans %}
            </a>
        {% endif %}
    </div>


    {{ form_errors(form) }}
    <div class="card mb-3">
        <div class="card-header">
            {% trans %}Master data{% endtrans %}
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-6">
                    {{ form_row(form.number) }}
                    {{ form_row(form.gender) }}
                </div>
                <div class="col-md-6">
                    {{ form_row(form.leader) }}
                </div>
            </div>
        </div>
    </div>

    {% if workingGroup.id %}
        <div class="row">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        {% trans %}Persons{% endtrans %}
                    </div>
                    <div class="card-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>{% trans %}Lastname{% endtrans %}</th>
                                    <th>{% trans %}Firstname{% endtrans %}</th>
                                    <th>{% trans %}DOB{% endtrans %}</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for person in workingGroup.persons %}
                                    <tr>
                                        <td>{{ person.address.familyName }}</td>
                                        <td>{{ person.firstname }}</td>
                                        <td>{{ person.dob ? person.dob | format_date('medium') : '' }}</td>
                                    </tr>
                                    {% else %}
                                        <tr>
                                            <td colspan="3">{% trans %}There are no entries existing, yet.{% endtrans %}</td>
                                        </tr>
                                    {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
    {{ form_end(form) }}

{% endblock %}

templates/working_group/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {% trans %}Working groups{% endtrans %} - {{ parent() }}
{% endblock %}

{% block body -%}
    <div class="d-flex align-items-center mb-3">
        <h2 class="mr-auto">
            {% trans %}Working groups{% endtrans %}
        </h2>
        <a class="btn btn-success" href="{{ path('app.workinggroup.new') }}">
            <i class="bi bi-plus-lg"></i>
        </a>
    </div>

    <table class="table table-bordered">
        <thead>
            <tr>
                <th>{% trans %}Group{% endtrans %}</th>
                <th>{% trans %}Leader{% endtrans %}</th>
                <th>{% trans %}Persons{% endtrans %}</th>
                <th class="col-md-2">{% trans %}Actions{% endtrans %}</th>
            </tr>
        </thead>
        <tbody>
        {% for working_group in working_groups %}
            <tr>
                <td>
                    <p>
                        {{ working_group.number }}.
                        {{ (working_group.gender == 'f' ? 'Group of Women' : 'Group of Men') | trans }}
                    </p>
                    <p class="text-muted">
                        {% trans %}Average Age{% endtrans %}: {{ working_group.avgAge | round(2) }}<br/>
                        {% trans %}Variance of Age{% endtrans %}: {{ working_group.varianceOfAge | round(2) }}<br/>
                        {% trans %}Standard Deviation of Age{% endtrans %}: {{ working_group.standardDeviationOfAge | round(2) }}<br/>
                    </p>
                </td>
                <td>
                    {% if working_group.leader %}
                        <a href="{{ path('app.address.edit', {'id': working_group.leader.address.id}) }}">
                            {{ working_group.leader.firstname ~ ' ' ~ working_group.leader.address.familyName }}
                            {% if working_group.leader.dob %}
                                ({{ working_group.leader.dob.format('Y') }})
                            {% endif %}
                        </a>
                    {% endif %}
                </td>
                <td>
                    <div class="row">
                        <div class="col-xl-6">
                            {% set numberOfMembers = (working_group.persons | length) - (working_group.persons.contains(working_group.leader) ? 1 : 0) %}
                            {% set sortedPersons = working_group.persons | sort((a, b) => a.lastnameAndFirstname <=> b.lastnameAndFirstname) %}
                            {% for person in (sortedPersons | filter(p => working_group.leader is not same as(p))) %}
                                <span class="text-muted">{{ loop.index }}.</span>
                                <a href="{{ path('app.address.edit', {'id': person.address.id}) }}">
                                    {{ person.lastnameFirstnameAndDob }}
                                </a><br/>

                                {% if loop.index == (numberOfMembers / 2) | round %}
                                    </div><div class="col-xl-6">
                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                </td>
                <td>
                    <a class="btn btn-outline-dark" href="{{ path('app.workinggroup.edit', { 'id': working_group.id }) }}">
                        <i class="bi bi-pencil"></i>
                    </a>
                    <a class="btn btn-danger"
                     href="{{ path('app.workinggroup.delete', { 'id': working_group.id }) }}"
                     onclick="return confirm('{% trans %}Do you really want to delete this entry?{% endtrans %}')">
                        <i class="bi bi-trash"></i>
                    </a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">
                    {% trans %}There are no entries existing, yet.{% endtrans %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/working_group/persons_unable_to_work.html.twig
{% extends 'base.html.twig' %}

{% block body -%}
    <h2>{% trans %}Persons that are unable to work{% endtrans %}</h2>

    <form action="{{ path('app.workinggroup.update_worker_status') }}" method="post">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>{% trans %}Last Name{% endtrans %}</th>
                    <th>{% trans %}First Name{% endtrans %}</th>
                    <th>{% trans %}DOB{% endtrans %}</th>
                    <th>{% trans %}Work Status{% endtrans %}</th>
                    <th>{% trans %}Group{% endtrans %}</th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <tbody>
            {% for person in persons %}
                <tr>
                    <td>
                        {{ person.address.familyName }}
                    </td>
                    <td>
                        {{ person.firstname }}
                    </td>
                    <td>
                        {{ person.dob ? person.dob | format_date('medium') : '' }}
                    </td>
                    <td>
                        <select name="worker_status[{{ person.id }}]">
                            {% for code,name in person.allWorkerStatus %}
                                <option value="{{ code }}" {% if code == person.workerStatus %}selected{% endif %}>
                                    {{ name | trans }}
                                </option>
                            {% endfor %}
                        </select>
                    </td>
                    <td>
                        <a class="btn btn-sm btn-outline-dark" href="{{ path('app.person.edit', {'id': person.id}) }}">
                            <i class="bi bi-pencil"></i>
                        </a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="4">
                        {% trans %}There are no entries existing, yet.{% endtrans %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <button type="submit" class="btn btn-primary">
            {% trans %}Save{% endtrans %}
        </button>
    </form>
{% endblock %}