src/Entity/Person.php
<?php

namespace App\Entity;

use App\Entity\Address;
use App\Entity\Ministry;
use App\Entity\WorkingGroup;
use App\Repository\PersonRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use libphonenumber\PhoneNumber;
use Symfony\Component\Serializer\Attribute as Serializer;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * App\Entity\Person
 */
#[ORM\Entity(repositoryClass: PersonRepository::class)]
#[ORM\Table(name: 'person')]
#[Gedmo\Loggable]
class Person
{
    /**
     * Import timestampable behavior.
     */
    use TimestampableEntity;

    const GENDER_MALE = 'm';
    const GENDER_FEMALE = 'f';

    /**
     * Persons whose working status depends on their age.
     */
    const WORKER_STATUS_UNTIL_AGE_LIMIT = 1;

    /**
     * People younger than the age limit years, but not able to work.
     */
    const WORKER_STATUS_INVALID = 2;

    /**
     * People having other ministries like deacons or elders.
     */
    const WORKER_STATUS_OTHER_MINISTRIES = 3;

    /**
     * People not able to work, because of their residence.
     */
    const WORKER_STATUS_UNABLE_RESIDENCE = 4;

    #[ORM\Id]
    #[ORM\Column(type: 'integer')]
    #[ORM\GeneratedValue]
    #[Serializer\Groups(['MinistryCategoryListing'])]
    private ?int $id = null;

    /**
     * Last name can be empty. In that case the last name is taken from
     * address entity (family name)
     */
    #[ORM\Column(type: 'string', length: 30, nullable: true)]
    #[Assert\Length(max: 30)]
    #[Gedmo\Versioned]
    private ?string $lastname = null;

    #[ORM\Column(type: 'string', length: 30)]
    #[Assert\Length(max: 30)]
    #[Gedmo\Versioned]
    #[Serializer\Groups(['MinistryCategoryListing'])]
    private ?string $firstname = null;

    /**
     * Date of birth
     */
    #[ORM\Column(type: 'date', nullable: true)]
    #[Gedmo\Versioned]
    #[Serializer\Groups(['MinistryCategoryListing'])]
    private ?\DateTime $dob = null;

    /**
     * Gender ('m' or 'f')
     */
    #[ORM\Column(type: 'string', length: 1)]
    #[Gedmo\Versioned]
    private ?string $gender = null;

    #[ORM\Column(type: 'phone_number', nullable: true)]
    #[Gedmo\Versioned]
    private ?PhoneNumber $mobile = null;

    #[ORM\Column(type: 'string', length: 100, nullable: true)]
    #[Assert\Email]
    #[Assert\Length(max: 100)]
    #[Gedmo\Versioned]
    private ?string $email = null;

    #[ORM\ManyToOne(targetEntity: Address::class, inversedBy: 'persons', cascade: ['persist'])]
    #[ORM\JoinColumn(name: 'address_id', nullable: false)]
    #[Gedmo\Versioned]
    #[Serializer\Groups(['MinistryCategoryListing'])]
    private ?Address $address = null;

    #[ORM\ManyToOne(targetEntity: 'WorkingGroup', inversedBy: 'persons')]
    #[ORM\JoinColumn(name: 'working_group_id', nullable: true, onDelete: 'SET NULL')]
    #[Gedmo\Versioned]
    private ?WorkingGroup $workingGroup = null;

    /**
     * Defines whether person is able to work or not.
     * See class constants self::WORKER_STATUS_*
     */
    #[ORM\Column(name: 'worker_status', type: 'smallint', nullable: false)]
    #[Gedmo\Versioned]
    private int $workerStatus = self::WORKER_STATUS_UNTIL_AGE_LIMIT;

    /**
     * @var string|null
     */
    #[ORM\Column(type: 'text', nullable: true)]
    private ?string $notice = null;

    #[ORM\Column(type: 'integer', nullable: true, unique: true)]
    private ?int $churchToolsId = null;

    #[ORM\OneToOne(targetEntity: 'WorkingGroup', mappedBy: 'leader')]
    private ?WorkingGroup $leaderOf = null;

    #[ORM\ManyToMany(targetEntity: 'Ministry', mappedBy: 'responsibles', cascade: ['remove'])]
    private Collection $ministries;

    /**
     * Constructor
     */
    public function __construct(?Address $address = null)
    {
        $address && $this->setAddress($address);
        $this->ministries = new ArrayCollection();
    }

    /**
     * Get id
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(?string $lastname): self
    {
        $this->lastname = $lastname;
        return $this;
    }

    /**
     * Get the firstname, name prefix and lastname concated.
     *
     * @return string
     */
    public function getFirstnameAndLastname(): string
    {
        return $this->getFirstname() . ' '
            . ($this->getAddress()->getNamePrefix() ? $this->getAddress()->getNamePrefix() . ' ' : '')
            . ($this->getLastname() ?: $this->getAddress()->getFamilyName());
    }

    /**
     * Get the display name (firstname and lastname) with year of birth.
     */
    public function getDisplayNameDob(): string
    {
        $year = $this->getDob() ? $this->getDob()->format('Y') : '0000';
        return $this->getFirstnameAndLastname() . ' (' . $year . ')';
    }

    /**
     * Get the concated lastname, firstname and name prefix.
     */
    public function getLastnameAndFirstname(): string
    {
        return ($this->getLastname() ?: $this->getAddress()->getFamilyName()) . ', ' . $this->getFirstname()
            . ($this->getAddress()->getNamePrefix() ? ' ' . $this->getAddress()->getNamePrefix() : '');
    }

    /**
     * Get the concated lastname, firstname, name prefix and year of birth.
     *
     * @return string
     */
    public function getLastnameFirstnameAndDob(): string
    {
        $year = $this->getDob() ? $this->getDob()->format('Y') : '0000';
        return $this->getLastnameAndFirstname() . ' (' . $year . ')';
    }

    /**
     * Set firstname
     *
     * @param string $firstname
     * @return Person
     */
    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    /**
     * Get firstname
     */
    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    /**
     * Set the date of birth
     *
     * @return $this
     */
    public function setDob(?\DateTime $dob): self
    {
        $this->dob = $dob;

        return $this;
    }

    /**
     * Get the date of birth
     */
    public function getDob(): ?\DateTime
    {
        return $this->dob;
    }

    /**
     * Get the current age of the person.
     */
    public function getAge(): ?int
    {
        if (!$this->dob) {
            return null;
        }

        $diff = $this->dob->diff(new \DateTime(), true);
        /* @var $diff \DateInterval */

        return $diff->y;
    }

    public function getGender(): ?string
    {
        return $this->gender;
    }

    public function setGender(?string $gender)
    {
        $this->gender = $gender;
        return $this;
    }

    /**
     * Set mobile
     *
     * @return $this
     */
    public function setMobile(?PhoneNumber $mobile): self
    {
        if ($this->mobile && $mobile && $this->mobile->equals($mobile)) {
            return $this;
        }

        $this->mobile = $mobile;

        return $this;
    }

    /**
     * Get mobile
     */
    public function getMobile(): ?PhoneNumber
    {
        return $this->mobile;
    }

    /**
     * Set email
     *
     * @return $this
     */
    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Get email
     */
    public function getEmail(): ?string
    {
        return $this->email;
    }

    /**
     * Set address
     *
     * @return $this
     */
    public function setAddress(Address $address): self
    {
        $this->address = $address;
        if (!$address->getPersons()->contains($this)) {
            $address->getPersons()->add($this);
        }
        return $this;
    }

    /**
     * Get address
     */
    public function getAddress(): ?Address
    {
        return $this->address;
    }

    /**
     * Set workingGroup
     *
     * @return $this
     */
    public function setWorkingGroup(?WorkingGroup $workingGroup): self
    {
        if ($this->gender && $workingGroup && $this->gender !== $workingGroup->getGender()) {
            throw new \InvalidArgumentException('This person is not compatible to the passed working group.');
        }

        $this->workingGroup = $workingGroup;

        if ($workingGroup && !$workingGroup->getPersons()->contains($this)) {
            $workingGroup->getPersons()->add($this);
        }

        return $this;
    }

    /**
     * Get workingGroup
     *
     * @return WorkingGroup
     */
    public function getWorkingGroup(): ?WorkingGroup
    {
        return $this->workingGroup;
    }

    public function getWorkerStatus(): int
    {
        return $this->workerStatus;
    }

    public function setWorkerStatus(int $workerStatus): self
    {
        $allStatus = self::getAllWorkerStatus();
        if (!isset($allStatus[$workerStatus])) {
            throw new \InvalidArgumentException('Given worker status is invalid.');
        }
        $this->workerStatus = $workerStatus;
        return $this;
    }

    /**
     * Get the notice.
     *
     * @return string|null
     */
    public function getNotice(): ?string
    {
        return $this->notice;
    }

    /**
     * Set the notice
     */
    public function setNotice(?string $notice)
    {
        $this->notice = $notice;
    }

    public function getChurchToolsId(): ?int
    {
        return $this->churchToolsId;
    }

    public function setChurchToolsId(int $churchToolsId): static
    {
        if ($this->churchToolsId && $this->churchToolsId !== $churchToolsId) {
            throw new \LogicException('The ChurchTools ID cannot be changed.');
        }

        $this->churchToolsId = $churchToolsId;
        return $this;
    }

    /**
     * @return array<int, string>
     */

src/Controller/AddressController.php
<?php

namespace App\Controller;

use App\Entity\Address;
use App\Form\AddressType;
use App\Helper\PersonHelper;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormFactoryInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Contracts\Translation\TranslatorInterface;

/**
 * Address controller.
 */
#[Route(path: '/address')]
class AddressController extends AbstractController
{
    public function __construct(
        private readonly TranslatorInterface $translator,
        private readonly PaginatorInterface $paginator,
        private readonly EntityManagerInterface $entityManager,
        private readonly FormFactoryInterface $formFactory
    ) {
    }

    /**
     * Lists all Address entities.
     */
    #[Route(path: '/index', name: 'app.address.index', defaults: ['_locale' => 'de'])]
    public function index(Request $request, PersonHelper $personHelper): Response
    {
        $repo = $this->entityManager->getRepository(Address::class); /* @var $repo \App\Repository\AddressRepository */
        $filterForm = $this->createFilterForm([
            'sort' => 'address.familyName',
        ]);
        $filterForm->handleRequest($request);

        $filter = $filterForm->getData();//$request->query->all('filter', []);
        if (!empty($filter['noPhoto'])) {
            $filter['noPhoto'] = $personHelper->getPersonIdsWithoutPhoto();
        }

        $pagination = $this->paginator->paginate(
            $repo->getListFilterQb($filter),
            $request->query->get('page', 1)/*page number*/,
            15, /*limit per page*/
            [
                'wrap-queries' => true,
                PaginatorInterface::DEFAULT_SORT_FIELD_NAME => [$filter['sort'], 'person.dob'],
                PaginatorInterface::DEFAULT_SORT_DIRECTION => 'asc',
            ]
        );

        if ($pagination->count() === 1) {
            return $this->redirectToRoute('app.address.edit', [
                'id' => $pagination[0]->getId(),
            ]);
        }

        return $this->render('/address/index.html.twig', array(
            'pagination' => $pagination,
            'person_ids_without_photo' => $personHelper->getPersonIdsWithoutPhoto(),
            //'persons_with_picture' => $personsWithPicture,
            'filterForm' => $filterForm,
        ));
    }

    /**
     * Displays a form to create a new Address entity.
     */
    #[Route(path: '/new', name: 'app.address.new', methods: ['GET', 'POST'])]
    public function new(Request $request): Response
    {
        $address = new Address();
        $form = $this->createForm(AddressType::class, $address, ['method' => 'POST']);
        $form->handleRequest($request);

        if ($form->isSubmitted()) {
            if ($form->isValid()) {
                $this->entityManager->persist($address);
                $this->entityManager->flush();

                $this->addFlash('success', 'The entry has been created.');

                return $this->redirectToRoute('app.address.edit', ['id' => $address->getId()]);
            }

            $this->addFlash('error', 'The submitted data is invalid. Please check your inputs.');
        }

        return $this->render('address/form.html.twig', [
            'entity' => $address,
            'form' => $form->createView(),
        ]);
    }

    /**
     * Displays a form to edit an existing Address entity.
     */
    #[Route(path: '/{id}/edit', name: 'app.address.edit', methods: ['GET', 'POST'])]
    public function edit(Address $address, Request $request, PersonHelper $personHelper): Response
    {
        $form = $this->createForm(AddressType::class, $address);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->entityManager->flush();

            // person picture file
            foreach ($request->files->get('person-picture-file', []) as $index => $file) {
                /** @var UploadedFile $file */
                $person = $address->getPersons()->get($index);

                if (!$file) {
                    continue;
                }

                if ($this->isJpegImage($file)) {
                    $file->move($personHelper->getPersonPhotoPath(), $personHelper->getPersonPhotoFilename($person));
                } else {
                    $this->addFlash('warning', $this->translator->trans(
                        'The uploaded photo for "%name%" is not a valid JPEG file.',
                        ['%name%' => $person->getFirstname()]
                    ));
                }
            }

            $this->addFlash('success', 'All changes have been saved.');

            return $this->redirectToRoute('app.address.edit', [
                'id' => $address->getId(),
                'referrer' => $request->query->get('referrer'),
            ]);
        }

        $repo = $this->entityManager->getRepository(Address::class);

        return $this->render('address/form.html.twig', [
            'entity' => $address,
            'form' => $form->createView(),
            'addressLogs' => $repo->findLogEntries($address),
            'personsLogs' => $repo->findPersonsLogEntries($address),
        ]);
    }

    /**
     * Deletes a Address entity.
     */
    #[Route(path: '/{id}/delete', name: 'app.address.delete')]
    public function delete(Address $address, Request $request): Response
    {

        foreach ($address->getPersons() as $person) {
            if ($person->getLeaderOf()) {
                $person->getLeaderOf()->setLeader(null);
            }
        }

        $this->entityManager->remove($address);
        $this->entityManager->flush();

        $this->addFlash('success', 'The entry has been deleted.');

        if ($referrer = $request->query->get('referrer')) {
            return $this->redirect($referrer);
        }

        return $this->redirectToRoute('app.address.index');
    }

    /**
     * Check if an uploaded file is real jpeg image.
     */
    private static function isJpegImage(UploadedFile $file): bool
    {
        $res = @imagecreatefromjpeg($file->getPathname());

        return $res !== false;
    }

    private function createFilterForm(array $data): FormInterface
    {
        $data['sortBy'] ??= 'address.familyName';

        $builder = $this->formFactory->createNamedBuilder(
            name: '',
            data: $data,
            options: [
                'block_prefix' => 'filter',
                'method' => 'get',
                'csrf_protection' => false,
            ]
        );

        $builder->add('term', TextType::class, [
            'required' => false,
            'attr' => [
                'placeholder' => 'Search Term',
            ],
        ]);

        $builder->add('hasEmail', CheckboxType::class, [
            'required' => false,
            'label' => 'Has Email Address',
        ]);

        $builder->add('noPhoto', CheckboxType::class, [
            'required' => false,
            'label' => 'Without Photo'
        ]);

        $builder->add('sort', ChoiceType::class, [
            'choices' => [
                'Name' => 'address.familyName',
                'Creation date' => 'person.createdAt',
            ],
        ]);

        $builder->add('direction', ChoiceType::class, [
            'choices' => [
                'ascending' => 'asc',
                'descending' => 'desc',
            ],
        ]);

        return $builder->getForm();
    }
}

templates/address/form.html.twig
{% extends 'base.html.twig' %}

{% form_theme form _self %}

{% block title %}
    {% trans %}Address{% endtrans %} - {{ parent() }}
{% endblock %}

{% block form_widget_remove_btn %}
{% apply spaceless %}
    {% if widget_remove_btn.wrapper_div is not same as(false) %}
        <div class="col-md-2">
    {% endif %}
    {% if widget_remove_btn|default(null) %}
    {% set button_type = 'remove' %}
    {% set button_values = widget_remove_btn %}
    {{ block('collection_button') }}
    {% endif %}
    {% if form.parent.vars['name'] == 'persons' and form.vars['data'] and form.vars['data'].id %}
        {% set person = form.vars['data'] %}
        <a class="btn btn-outline-dark" href="{{ path('app.person.edit', {'id': person.id}) }}">
            <i class="bi bi-pencil"></i> {% trans %}Edit{% endtrans %}
        </a>
    {% endif %}
    {% if widget_remove_btn.wrapper_div is not same as(false) %}
        </div>
    {% endif %}
{% endapply %}
{% endblock %}

{% block person_widget %}
    {% set person = form.vars['data'] %}
    <div class="row">
        <div class="col-md-3">
            <p>
                <img class="-person-picture img-thumbnail"
                 src="{{ person and person.id ? path('app.person.optimized_member_picture', {'id': person.id}) : '#' }}"
                 alt="No Image"/>
            </p>
            <p>
                <input type="file" name="person-picture-file[{{ name }}]" />
            </p>
        </div>
        <div class="col-md-3">
            {{ form_row(form.lastname) }}
            {{ form_row(form.firstname) }}
            {{ form_row(form.dob) }}
            {{ form_row(form.gender) }}
            {{ form_row(form.mobile) }}
            {{ form_row(form.email) }}
        </div>
        <div class="col-md-3">
            {{ block('form_widget') }}
            {% if person %}
                <div class="form-group">
                    <label for="address_persons_{{ person.id }}_churchToolsId">
                        {% trans %}ChurchTools ID{% endtrans %}
                    </label>
                    <input type="text"
                           class="form-control"
                           id="address_persons_{{ person.id }}_churchToolsId"
                           value="{{ person.churchToolsId }}"
                           disabled>
                </div>
            {% endif %}
        </div>
        <div class="col-md-3 text-right">
            {% if person and person.id %}
                <a class="btn btn-sm btn-outline-dark" href="{{ path('app.person.edit', {'id': person.id}) }}">
                    <i class="bi bi-pencil"></i> {% trans %}Edit{% endtrans %}
                </a>
            {% endif %}
            <button type="button" class="btn btn-sm btn-danger" remove-collection-item>
                <i class="bi bi-trash"></i> {% trans %}Remove{% endtrans %}
            </button>
        </div>
    </div>
{% endblock %}

{% block body -%}
    <form method="post" enctype="multipart/form-data">
        <div class="d-flex align-items-center mb-3">
            <div class="mr-auto">
                <h2>{% trans %}Edit Address{% endtrans %}</h2>
            </div>
            <a class="btn btn-outline-dark mr-2" href="{{ app.request.query.get('referrer', path('app.address.index')) }}" title="{% trans %}Back to List{% endtrans %}">
                <i class="bi bi-chevron-left"></i> {% trans %}Back{% endtrans %}
            </a>
            <button type="submit" class="btn btn-primary mr-2">
                <i class="bi bi-save"></i> {% trans %}Save{% endtrans %}
            </button>

            {% if entity.id > 0 %}
                <a class="btn btn-danger"
                 href="{{ path('app.address.delete', {'id': entity.id, 'referrer': app.request.query.get('referrer')}) }}"
                 title="{% trans %}Delete Address{% endtrans %}"
                 onclick="return confirm('{% trans %}Do you really want to delete this entry?{% endtrans %}')">
                    <i class="bi bi-trash"></i> {% trans %}Delete{% endtrans %}
                </a>
            {% endif %}
        </div>

        {{ form_errors(form) }}
        <div class="card">
            <div class="card-header">{% trans %}Master data{% endtrans %}</div>
            <div class="card-body">
                <div class="row">
                    <div class="col-lg-6">
                        {{ form_row(form.namePrefix) }}
                        {{ form_row(form.familyName) }}
                    </div>
                    <div class="col-lg-6">
                        {{ form_row(form.phone) }}
                        {{ form_row(form.street) }}
                        {{ form_row(form.zip) }}
                        {{ form_row(form.city) }}
                    </div>
                </div>
            </div>
        </div>
        <div class="card my-4">
            <div class="card-header">
                {% trans %}Persons{% endtrans %}
            </div>
            <div class="card-body">
                {{ form_row(form.persons) }}

                <button type="button" class="btn btn-sm btn-primary" add-collection-item="#{{ form.persons.vars.id }}">
                    <i class="bi bi-plus-lg"></i> {% trans %}Add person{% endtrans %}
                </button>
            </div>
        </div>
        {{ form_rest(form) }}
    </form>

    {% if entity.id > 0 %}
        {% set allLogs = [{'person': null, 'logs': addressLogs}] | merge(personsLogs) %}
        {% for personAndLogs in (allLogs | filter(t => t.logs|length > 0)) %}
            <div class="card mb-4">
                <div class="card-header">
                    {% if personAndLogs.person is null %}
                        {% trans %}Change history of address{% endtrans %}
                    {% else %}
                        {% trans with {'%name%': personAndLogs.person.firstnameAndLastname} %}Change history of %name%{% endtrans %}
                    {% endif %}
                </div>
                <div class="card-body">
                    <table class="table table-bordered">
                        <tr>
                            <th>{% trans %}Timestamp{% endtrans %}</th>
                            <th>{% trans %}Action{% endtrans %}</th>
                            <th>{% trans %}Data changes{% endtrans %}</th>
                        </tr>
                        {% for log in (personAndLogs.logs | default([])) %}
                            <tr>
                                <td>{{ log.loggedAt | format_datetime('medium', 'medium') }}</td>
                                <td>{{ log.action }}</td>
                                <td class="p-0">
                                    <table class="table table-borderless table-striped m-0">
                                        {% for key, value in (log.data | filter(v => v is not empty or log.action == 'update')) %}
                                            <tr>
                                                <td class="w-25">{{ key | capitalize | trans }}</td>
                                                <td>
                                                    {% if value is null or value is same as ('') %}
                                                        {% if log.action == 'update' %}
                                                            - {% trans %}removed{% endtrans %} -
                                                        {% endif %}
                                                    {% elseif key in ['address', 'workingGroup'] %}
                                                        ID: {{ value.id }}
                                                    {% elseif value.format is defined %}
                                                        {{ value | format_date('medium') }}
                                                    {% elseif value.getRawInput is defined %}
                                                        {{ value | phone_number_format }}
                                                    {% else %}
                                                        {{ value }}
                                                    {% endif %}
                                                </td>
                                            </tr>
                                        {% endfor %}
                                    </table>
                                </td>
                            </tr>
                        {% else %}
                            <tr>
                                <td colspan="3">
                                    {% trans %}There are no entries existing, yet.{% endtrans %}
                                </td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        {% endfor %}
    {% endif %}
{% endblock %}